### ISSUE TITLE
How to use httpid and jq within docker?

### ISSUE THREAD

**Issue by leo18945** [blacktop/httpie#1]
How to use httpid and jq within docker?

**I want to get the ip only in json result like '34.10.12.40'**

```
docker run -it --rm blacktop/httpie -b ifconfig.co/json
{
    "country": "United States",
    "country_eu": false,
    "country_iso": "US",
    "hostname": "lqwtx.com",
    "ip": "34.10.12.40",
    "ip_decimal": 39585,
    "latitude": 35,
    "longitude": 105
}
```
but I've tried some ways but does not work, like blow. 

`docker run -it --rm blacktop/httpie ash -c "http -b ifconfig.co/json | jq '.ip’”`

`docker run -it --rm blacktop/httpie -b ifconfig.co/json jq '.ip'`

**Comment by blacktop** [comment]
```bash
$ docker run -it --rm --entrypoint=sh blacktop/httpie -c "http ifconfig.co/json | jq .ip"
```

**Comment by leo18945** [comment]
Ok, thanks. That's what I want.
